src/objects/Log__e.object
<CustomObject>
    <description>Logs</description>
    <fields>
        <fullName>num_Line__c</fullName>
        <label>Line</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>txl_Message__c</fullName>
        <label>Message</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>txt_Class__c</fullName>
        <label>Class</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>txt_Context__c</fullName>
        <label>Context</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>txt_Level__c</fullName>
        <defaultValue>&quot;DEBUG&quot;</defaultValue>
        <label>Level</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>txt_Method__c</fullName>
        <label>Method</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>txt_User__c</fullName>
        <label>User</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Log</label>
    <pluralLabel>Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log__e/fields/txl_Data__c.field-meta.xml
<CustomField>
    <fullName>txl_Data__c</fullName>
    <defaultValue>&quot;{}&quot;</defaultValue>
    <label>Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>dat_LogViaEvents__c</fullName>
        <label>Log via Platform Events on</label>
        <type>Date</type>
    </fields>
    <label>Settings</label>
</CustomObject>

force-app/main/default/classes/Log_Test.cls
@IsTest
private class Log_Test {

	@IsTest
	private static void debug() {

		// Setup
		enableLogEvents(System.today());

		String message = '{0}=={1}:{2}';
		List<Object> values = new List<Object>{ 1, '2', false };
		insert new Account(Name = 'Acme');


		// Execute
		Log.debug(message, values);


		// Verify
		Log__e log = Log.currentEvent();
		System.assertEquals(UserInfo.getUserId(), log.txt_User__c);
		System.assertEquals(LoggingLevel.DEBUG.name(), log.txt_Level__c);
		System.assertEquals(Request.getCurrent().getRequestId() + '/' + Request.getCurrent().getQuiddity(), log.txt_Context__c);

		System.assertEquals('1==2:false', log.txl_Message__c);
		System.assertEquals(thisClassName(), log.txt_Class__c);
		System.assertEquals('debug', log.txt_Method__c);
		System.assertEquals(16, log.num_Line__c);

		Map<String, Object> data = data(log);
		System.assertEquals('1==2:false', (String) data.get('Message'));
		System.assertEquals(thisClassName(), (String) data.get('Class'));
		System.assertEquals('debug', (String) data.get('Method'));
		System.assertEquals(16, (Integer) data.get('Line'));
		System.assertEquals(2, (Integer) data.get('DMLRows')); // 1x Settings__c + 1x Log__e
	}


	@IsTest
	private static void error() {

		// Setup
		enableLogEvents(System.today());


		// Execute
		Log.error('');


		// Verify
		System.assertEquals(LoggingLevel.ERROR.name(), Log.currentEvent().txt_Level__c);
	}


	@IsTest
	private static void timestampWhenNoContextId() {

		// Setup
		enableLogEvents(System.today());


		// Execute
		Log.debug('');


		// Verify
		System.assertNotEquals(null, Log.currentEvent().txt_Context__c);
	}


	@IsTest
	private static void noEventsSendWhenDisabled() {

		// Execute
		Log.debug('');


		// Verify
		System.assertEquals(null, Log.currentEvent());

	}


	@IsTest
	private static void noEventsWhenExpired() {

		// Setup
		enableLogEvents(yesterDay());


		// Execute
		Log.debug('');


		// Verify
		System.assertEquals(null, Log.currentEvent());

	}


	// HELPER

	private static void enableLogEvents(Date day) {
		insert new Settings__c(SetupOwnerId = UserInfo.getUserId(), dat_LogViaEvents__c = day);
	}


	private static Date yesterDay() {
		return System.today().addDays(-1);
	}


	private static String thisClassName() {
		String ns = [SELECT NamespacePrefix FROM Organization].NamespacePrefix + '.';
		return Log_Test.class.getName().removeStart(ns);
	}


	private static Map<String, Object> data(Log__e log) {
		return (Map<String, Object>) JSON.deserializeUntyped(log.txl_Data__c);
	}
}